var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(Pages)/services/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__a1f8fd0c._.js")
R.c("server/chunks/ssr/_586d3bb7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__752a7495._.js")
R.c("server/chunks/ssr/_472c1382._.js")
R.c("server/chunks/ssr/[root-of-the-server]__12fee31f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__85eeb158._.js")
R.c("server/chunks/ssr/node_modules_next_dist_81959fb0._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__57606222._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_(Pages)_services_page_actions_09ee2d59.js")
R.m(55388)
module.exports=R.m(55388).exports
