services:
  web:
    build:
      context: .
      target: ${BUILD_TARGET:-dev}          # dev | runner
    image: k-web:${BUILD_TARGET:-dev}
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      NEXT_TELEMETRY_DISABLED: "1"
    volumes:
      - ${DEV_MOUNT:-.:/app}
      # - ${DEV_NODEMODULES_MOUNT:-/app/node_modules} # this is thought to be handled in Dockerfile now
    command: ${APP_CMD:-npm run dev}
    depends_on:
      mongo:
        condition: service_healthy
    profiles:
      - ${COMPOSE_PROFILES:-dev}
