import {
  FaCube,
  FaPlug,
  FaUsersCog,
  FaRegNewspaper,
  FaUsers,
  FaRegGem,
  FaLongArrowAltRight,
  FaMinus,
  FaPlus,
  FaMapPin,
  FaFacebook,
  FaLinkedin,
  FaYoutube,
  FaInstagram,
  FaPhoneAlt,
  FaEnvelope,
  FaAngleRight,
} from "react-icons/fa";

export {
  FaCube as CubeIcon,
  FaPlug as PlugIcon,
  FaUsersCog as UsersCogIcon,
  FaRegNewspaper as NewspaperIcon,
  FaUsers as UsersIcon,
  FaRegGem as GemIcon,
  FaLongArrowAltRight as ArrowRightIcon,
  FaMinus as MinusIcon,
  FaPlus as PlusIcon,
  FaMapPin as MapPinIcon,
  FaFacebook as FB,
  FaLinkedin as LinkedIn,
  FaYoutube as YouTube,
  FaInstagram as Instagram,
  FaPhoneAlt as PhoneIcon,
  FaEnvelope as MailIcon,
  FaAngleRight as AngleRightIcon,
};
