var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(Pages)/stop-the-stigma/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__a411cece._.js")
R.c("server/chunks/ssr/_472c1382._.js")
R.c("server/chunks/ssr/_404d7dce._.js")
R.c("server/chunks/ssr/[root-of-the-server]__12fee31f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__85eeb158._.js")
R.c("server/chunks/ssr/node_modules_next_dist_81959fb0._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__57606222._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_(Pages)_stop-the-stigma_page_actions_7a8d1c3a.js")
R.m(96181)
module.exports=R.m(96181).exports
