# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates the Microsoft Security DevOps CLI with GitHub code scanning.
# For documentation, visit https://aka.ms/msdo-github
name: Microsoft Security DevOps

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '43 21 * * 3'

permissions:
  contents: read

env:
  # Opt-in early to Node.js 24 for all JavaScript-based actions
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  MSDO-Scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Run Microsoft Security DevOps CLI
    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@v1
      id: msdo

    # Upload results to the Security tab
    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
