# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates a collection of open source static analysis tools
# with GitHub code scanning. For documentation, or to provide feedback, visit
# https://github.com/github/ossar-action
name: OSSAR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '43 21 * * 3'

permissions:
  contents: read

env:
  # Opt-in early to Node.js 24 for all JavaScript-based actions
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  OSSAR-Scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Run open-source static analysis tools
    - name: Run OSSAR
      uses: github/ossar-action@v2
      id: ossar

    # Upload SARIF results to Security tab
    - name: Upload OSSAR results
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}
